[package]
name = "driver"
version = "0.1.0"
edition = "2021"

[dependencies]
hypervisor = { path = "../hypervisor" }
log = "0.4"
wdk-sys = "0.3"
wdk-alloc = "0.3"
wdk-panic = "0.3"

[build-dependencies]
wdk-build = "0.3"

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.wdk.driver-model]
driver-type = "WDM"
